<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9</LangVersion>
    <Nullable>enable</Nullable>
    <DefineConstants>$(DefineConstants);LEGACY</DefineConstants>
    <LegacyPoolPath Condition="'$(LegacyPoolPath)' == ''">$(MSBuildThisFileDirectory)../../../src/CrowRx.Pool.Unity/Assets/Packages/CrowRx.Pool.1.0.4/lib/netstandard2.1/CrowRx.Pool.dll</LegacyPoolPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Program.cs" Link="Program.cs" />
    <Compile Include="../QueueOperationDiagnostics.cs" Link="QueueOperationDiagnostics.cs" />
    <Reference Include="CrowRx.Pool"><HintPath>$(LegacyPoolPath)</HintPath></Reference>
    <Reference Include="System.Text.Json">
      <HintPath>..\..\..\..\..\..\..\Unity\Editor\6000.5.1f1\Editor\Data\BCLExtensions\TargetingPacks\netstandard2.1\ref\System.Text.Json.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>