<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>9</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Program.cs" Link="Program.cs" />
    <Compile Include="../QueueOperationDiagnostics.cs" Link="QueueOperationDiagnostics.cs" />
    <ProjectReference Include="../../../src/CrowRx.Pool/CrowRx.Pool.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Text.Json">
      <HintPath>..\..\..\..\..\..\..\Unity\Editor\6000.5.1f1\Editor\Data\BCLExtensions\TargetingPacks\netstandard2.1\ref\System.Text.Json.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>